
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis_data:
